[package]
name = "libp2p-example"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
toml = "0.8.20"
serde = { version = "1.0.219", features = ["derive"] }
libp2p = "0.55.0"
